/*=============================================================================================
   PL/SQL Script: audit_logging.sql
===============================================================================================

   💡 Purpose:
   --------------------------------------------------------------------------------------------
   This script logs changes made to the `contracts` table into an audit table (`audit_log`) 
   to ensure traceability and compliance with data management policies.

   ✨ Features:
   --------------------------------------------------------------------------------------------
   ➜ Captures key details of changes, including the action performed, table name, timestamp, 
      and specifics of the modification.
   ➜ Robust error handling to ensure smooth execution and detailed feedback via `DBMS_OUTPUT`.

   🛠️ Execution Instructions:
   --------------------------------------------------------------------------------------------
   1️⃣ Save this script as `audit_logging.sql`.
   2️⃣ Open Oracle SQL Developer (or another PL/SQL-compatible environment).
   3️⃣ Enable server output by running:
       SET SERVEROUTPUT ON;
   4️⃣ Execute the script.
   5️⃣ Verify log entries in the `audit_log` table by running the following query:
       SELECT * FROM audit_log;

   ⚠️ Prerequisites:
   --------------------------------------------------------------------------------------------
   ⚙ Ensure the `audit_log` table exists before executing the script. The table should have 
      appropriate columns to capture action details, timestamps, and change specifics.
   ⚙ Check database permissions to allow insertion into the `audit_log` table.

=============================================================================================*/

/*~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
🟢 BEGINNING OF SCRIPT 🟢
-----------------------------------------------------------------------------------------------
The audit logging process starts here. Capture and preserve change details with precision 
to maintain compliance and traceability. Execute confidently! 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/

-- Create the audit log table (if not exists)
BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE audit_log (
            log_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            action VARCHAR2(100),
            table_name VARCHAR2(100),
            changed_at TIMESTAMP DEFAULT SYSTIMESTAMP,
            details VARCHAR2(4000)
        )';
    DBMS_OUTPUT.PUT_LINE('Audit log table created successfully.');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -955 THEN -- ORA-00955: name is already used by an existing object
            DBMS_OUTPUT.PUT_LINE('Audit log table already exists.');
        ELSE
            DBMS_OUTPUT.PUT_LINE('Error creating audit log table: ' || SQLERRM);
        END IF;
END;
/

-- Insert a sample log entry
BEGIN
    INSERT INTO audit_log (action, table_name, details)
    VALUES ('Cleaned Data', 'contracts', 'Removed duplicates and standardized fields.');
    DBMS_OUTPUT.PUT_LINE('Sample log entry inserted successfully.');
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error inserting log entry: ' || SQLERRM);
END;
/