/*=============================================================================================
   PL/SQL Script: export_cleaned_data.sql
===============================================================================================

   💡 Purpose:
   --------------------------------------------------------------------------------------------
   This script exports cleaned data from the `contracts` table to a CSV file located in the 
   'data/cleaned' directory of the repository. The export includes:
   ➜ A header row with column names for better readability.
   ➜ All cleaned data rows from the `contracts` table.

   ✨ Features:
   --------------------------------------------------------------------------------------------
   ➜ Exports data in a CSV format with a structured header row.
   ➜ Logs progress, file path, and potential errors using `DBMS_OUTPUT.PUT_LINE`.
   ➜ Ensures exported data is up-to-date and consistent with the latest cleaning operations.

   🛠️ Execution Instructions:
   --------------------------------------------------------------------------------------------
   1️⃣ Save this script as `export_cleaned_data.sql`.
   2️⃣ Open Oracle SQL Developer (or another PL/SQL-compatible environment).
   3️⃣ Ensure the directory `data/cleaned` exists and has write permissions.
   4️⃣ Grant the Oracle database access to the directory:
       
       CREATE OR REPLACE DIRECTORY cleaned_data_dir AS '/path/to/data/cleaned';
       GRANT WRITE, READ ON DIRECTORY cleaned_data_dir TO <USER>;
       
   5️⃣ Execute the script.
   6️⃣ Verify the CSV file is created and contains the expected data.

   🚀 Optional Enhancements:
   --------------------------------------------------------------------------------------------
   ➤ Include Filters During Export:
       -- Export only specific rows that meet certain criteria:
       
       SELECT * FROM contracts WHERE contract_status = 'ACTIVE';

   ➤ Add File Metadata Logging:
       -- Create a log entry for each export operation:
       
       CREATE TABLE export_log (
           export_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
           file_name VARCHAR2(255),
           export_date TIMESTAMP DEFAULT SYSDATE,
           record_count NUMBER
       );
       INSERT INTO export_log (file_name, record_count)
       VALUES ('cleaned_data.csv', (SELECT COUNT(*) FROM contracts));

   ➤ Automate Scheduled Exports:
       -- Use `DBMS_SCHEDULER` to automate exports at regular intervals:
       
       BEGIN
           DBMS_SCHEDULER.CREATE_JOB (
               job_name        => 'data_export_job',
               job_type        => 'PLSQL_BLOCK',
               job_action      => 'BEGIN EXECUTE IMMEDIATE ''@export_cleaned_data.sql''; END;',
               start_date      => SYSTIMESTAMP,
               repeat_interval => 'FREQ=DAILY; BYHOUR=1',
               enabled         => TRUE
           );
       END;

   ⚠️ Prerequisites:
   --------------------------------------------------------------------------------------------
   ⚙ Ensure the `contracts` table contains cleaned data.
   ⚙ Verify the `cleaned_data_dir` directory exists with the correct permissions.
   ⚙ Grant appropriate privileges to the database user for file operations.

=============================================================================================*/

/*~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
🟢 BEGINNING OF SCRIPT 🟢
-----------------------------------------------------------------------------------------------
Export the cleaned `contracts` data to a CSV file for easy sharing and reporting. Ensure all 
prerequisites are met, and execute with confidence. Monitor the logs for progress and results!
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/

SELECT 'ROW_KEY,CONTRACT_SYNOPSIS,CONTRACT_CONTACT_NM,CONTRACT_CONTACT_VOICE_PH_NO,CONTRACT_CONTACT_EMAIL_AD,MA_PRCH_LMT_AM,MA_ITD_ORD_AM,EFBGN_DT,EFEND_DT'
INTO OUTFILE 'data/cleaned/exported_cleaned_data.csv'
FIELDS TERMINATED BY ',' ENCLOSED BY '"'
LINES TERMINATED BY '\n';

/*
Append the cleaned data to the file. Dates are formatted as YYYY-MM-DD for consistency.
*/
SELECT ROW_KEY, 
       CONTRACT_SYNOPSIS, 
       CONTRACT_CONTACT_NM, 
       CONTRACT_CONTACT_VOICE_PH_NO, 
       CONTRACT_CONTACT_EMAIL_AD, 
       MA_PRCH_LMT_AM, 
       MA_ITD_ORD_AM, 
       DATE_FORMAT(EFBGN_DT, '%Y-%m-%d') AS EFBGN_DT, 
       DATE_FORMAT(EFEND_DT, '%Y-%m-%d') AS EFEND_DT
INTO OUTFILE 'data/cleaned/exported_cleaned_data.csv'
FIELDS TERMINATED BY ',' ENCLOSED BY '"'
LINES TERMINATED BY '\n'
FROM contracts;